//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donor2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public string Donor_ID { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Address { get; set; }
        public string Occupation { get; set; }
    }
}
